const quotes = [
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Believe you can and you're halfway there.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "It always seems impossible until it’s done.",
  "Push yourself, because no one else is going to do it for you.",
  "Dream big. Start small. Act now.",
  "Discipline is choosing between what you want now and what you want most.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Stay positive, work hard, make it happen.",
  "Do something today that your future self will thank you for.",
  "Don’t stop until you’re proud.",
  "Great things never come from comfort zones.",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t limit your challenges. Challenge your limits.",
  "Doubt kills more dreams than failure ever will.",
  "Start where you are. Use what you have. Do what you can.",
  "Stay focused and never give up.",
  "Work hard in silence, let success make the noise.",
  "The key to success is to focus on goals, not obstacles.",
  "Your only limit is your mind.",
  "Difficult roads often lead to beautiful destinations.",
  "Success is the sum of small efforts repeated daily.",
  "Don’t be afraid to fail. Be afraid not to try.",
  "You are stronger than you think.",
  "Action is the foundational key to all success.",
  "Make each day your masterpiece.",
  "Believe in yourself and all that you are.",
  "Small steps every day lead to big results.",
  "Stay hungry, stay foolish.",
  "Your dreams don’t work unless you do.",
  "Don’t wait for opportunity. Create it.",
  "Everything you can imagine is real.",
  "Success starts with self-discipline.",
  "Focus on progress, not perfection.",
  "Be stronger than your excuses.",
  "You miss 100% of the shots you don’t take.",
  "The harder you work, the luckier you get.",
  "Dream it. Wish it. Do it.",
  "Consistency is the key to success.",
  "Turn your dreams into plans.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Success is not for the lazy.",
  "Stay patient and trust your journey.",
  "Great things take time.",
  "Never stop learning.",
  "If it doesn’t challenge you, it won’t change you.",
  "Work until your idols become your rivals.",
  "Make today count.",
  "Don’t be busy, be productive.",
  "Success is a journey, not a destination.",
  "The best way out is always through.",
  "Start now. Not tomorrow.",
  "Your future is created by what you do today.",
  "Dream without fear, act without limits.",
  "Stay positive, even when it’s hard.",
  "Success requires sacrifice.",
  "Be fearless in the pursuit of greatness.",
  "Don’t let yesterday take up too much of today.",
  "You are capable of amazing things.",
  "Do what you love and never give up.",
  "Opportunities don’t happen, you create them.",
  "Stay focused on your goals.",
  "Be the hardest worker in the room.",
  "Never give up on your dreams.",
  "Success is earned, not given.",
  "Work hard, dream big.",
  "Your only competition is you.",
  "Don’t stop when you’re tired, stop when you’re done.",
  "Believe in the power of yet.",
  "You can do anything you set your mind to.",
  "Progress, not perfection.",
  "The secret of getting ahead is getting started.",
  "Keep going. Everything you need will come to you.",
  "Success is built on consistency.",
  "Be proud of how far you’ve come.",
  "Stay committed to your goals.",
  "Dream big and dare to fail.",
  "Every day is a second chance.",
  "Success begins with self-belief.",
  "You are your only limit.",
  "Make it happen.",
  "Focus. Work. Repeat.",
  "Nothing worth having comes easy.",
  "Keep pushing forward.",
  "Don’t give up. Great things take time.",
  "Be the energy you want to attract.",
  "Your mindset determines your success.",
  "Hard work always pays off.",
  "Start small, think big.",
  "Stay strong and never quit.",
  "Be consistent and stay patient.",
  "Success is a result of daily habits.",
  "Keep learning and growing.",
  "Chase your dreams, not people.",
  "Success is not luck, it’s effort."
];



const button = document.querySelector("button")
const quote = document.querySelector("h1")



button.addEventListener('click',()=>{
    const index = Math.floor(Math.random() * quotes.length);
    quote.textContent = quotes[index];
})